const menuItems = [
  {
    id: 1,
    name: "Potato Salad",
    description: "A classic potato salad made with fresh ingredients.",
    price: 20.0,
    image: "/PotatoSalad.webp",
    alt: "Potato Salad",
  },
  {
    id: 2,
    name: "BBQ Beans",
    description: "Rich and savory BBQ beans cooked to perfection.",
    price: 22.0,
    image: "/BBQBeans.webp",
    alt: "BBQ Beans",
  },
  {
    id: 3,
    name: "Green Beans",
    description: "Fresh green beans with a touch of seasoning.",
    price: 22.0,
    image: "/GreenBeans.webp",
    alt: "Green Beans",
  },
  {
    id: 4,
    name: "Mac & Cheese",
    description: "Creamy and cheesy mac & cheese, a crowd favorite.",
    price: 25.0,
    image: "/cropped-MacNCheese.webp",
    alt: "Mac & Cheese",
  },
  {
    id: 5,
    name: "Green Salad",
    description: "A refreshing green salad with a mix of fresh vegetables.",
    price: 20.0,
    image: "/GreenSalad.webp",
    alt: "Green Salad",
  },
  {
    id: 6,
    name: "Dinner Rolls",
    description: "Soft and fluffy dinner rolls, perfect for any meal.",
    price: 7.0,
    image: "/DinnerRolls.webp",
    alt: "Dinner Rolls",
  },
  {
    id: 7,
    name: "Sweet Potato Pie",
    description: "A delicious sweet potato pie, perfect for dessert.",
    price: 15.0,
    image: "/SweetPie.webp",
    alt: "Sweet Potato Pie",
  },
  {
    id: 8,
    name: "Banana Pudding",
    description: "Creamy and sweet banana pudding, a southern classic.",
    price: 30.0,
    image: "/BananaPuddingCrop.webp",
    alt: "Banana Pudding",
  },
  {
    id: 9,
    name: "Brisket",
    description: "Tender and juicy smoked brisket, perfect for any BBQ.",
    price: "$65.00 - $95.00",
    image: "/cropped-NewBrisket.webp",
    alt: "Brisket",
  },
  {
    id: 10,
    name: "Ribs",
    description: "Succulent smoked ribs with a rich, smoky flavor.",
    price: "$30.00/rack",
    image: "/Ribs.webp",
    alt: "Ribs",
  },
  {
    id: 11,
    name: "Chicken",
    description: "Delicious smoked chicken with a savory, smoky taste.",
    price: "$35.00 - $40.00",
    image: "/chicken.webp",
    alt: "Chicken",
  },
  {
    id: 12,
    name: "Sausage",
    description: "Smoked sausage with a perfect blend of spices.",
    price: "$16.00/lbs",
    image: "/sausagechopped.webp",
    alt: "Sausage",
  },
  {
    id: 13,
    name: "Wings",
    description: "Smoked wings with a crispy exterior and juicy interior.",
    price: "$35.00/30pcs",
    image: "/cropped-wings.webp",
    alt: "Wings",
  },
  {
    id: 14,
    name: "Whole Ham",
    description: "A whole smoked ham, perfect for gatherings.",
    price: "$60.00/each",
    image: "/ham.webp",
    alt: "Whole Ham",
  },
  {
    id: 15,
    name: "Smoked Turkey",
    description: "A whole smoked turkey, juicy and flavorful.",
    price: "$70.00/each",
    image: "/wholeturkey.webp",
    alt: "Smoked Turkey",
  },
  {
    id: 16,
    name: "Fried Turkey",
    description: "A whole fried turkey, crispy on the outside, tender on the inside.",
    price: "$80.00/each",
    image: "/friedTurkey.webp",
    alt: "Fried Turkey",
  },
  {
    id: 17,
    name: "Sandwiches",
    description: "Delicious sandwiches, perfect for any occasion.",
    price: "$50.00 - $80.00",
    image: "/sandwhiches-wrapped.webp",
    alt: "Sandwiches",
  },
];

export default menuItems;
